name: angel_file_security
version: 1.1.0
description: Middleware for securing file uploads.
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
homepage: https://github.com/angel-dart/file_security
dependencies:
  angel_framework: ">=1.1.0-alpha <2.0.0"
  http: ^0.11.3
dev_dependencies:
  angel_validate: ^1.0.0
  angel_test: ^1.1.0-alpha
  test: ^0.12.0
  uuid: ^0.5.3